interface NationalityItem {
  alpha_3_code: string
  nationality: string
}

const nationalitiesList: NationalityItem[] = [
  { alpha_3_code: 'AFG', nationality: 'Afghan' },
  { alpha_3_code: 'ALA', nationality: 'Åland Island' },
  { alpha_3_code: 'ALB', nationality: 'Albanian' },
  { alpha_3_code: 'DZA', nationality: 'Algerian' },
  { alpha_3_code: 'ASM', nationality: 'American Samoan' },
  { alpha_3_code: 'AND', nationality: 'Andorran' },
  { alpha_3_code: 'AGO', nationality: 'Angolan' },
  { alpha_3_code: 'AIA', nationality: 'Anguillan' },
  { alpha_3_code: 'ATA', nationality: 'Antarctic' },
  { alpha_3_code: 'ATG', nationality: 'Antiguan or Barbudan' },
  { alpha_3_code: 'ARG', nationality: 'Argentine' },
  { alpha_3_code: 'ARM', nationality: 'Armenian' },
  { alpha_3_code: 'ABW', nationality: 'Aruban' },
  { alpha_3_code: 'AUS', nationality: 'Australian' },
  { alpha_3_code: 'AUT', nationality: 'Austrian' },
  { alpha_3_code: 'AZE', nationality: 'Azerbaijani, Azeri' },
  { alpha_3_code: 'BHS', nationality: 'Bahamian' },
  { alpha_3_code: 'BHR', nationality: 'Bahraini' },
  { alpha_3_code: 'BGD', nationality: 'Bangladeshi' },
  { alpha_3_code: 'BRB', nationality: 'Barbadian' },
  { alpha_3_code: 'BLR', nationality: 'Belarusian' },
  { alpha_3_code: 'BEL', nationality: 'Belgian' },
  { alpha_3_code: 'BLZ', nationality: 'Belizean' },
  { alpha_3_code: 'BEN', nationality: 'Beninese, Beninois' },
  { alpha_3_code: 'BMU', nationality: 'Bermudian, Bermudan' },
  { alpha_3_code: 'BTN', nationality: 'Bhutanese' },
  { alpha_3_code: 'BOL', nationality: 'Bolivian' },
  { alpha_3_code: 'BES', nationality: 'Bonaire' },
  { alpha_3_code: 'BIH', nationality: 'Bosnian or Herzegovinian' },
  { alpha_3_code: 'BWA', nationality: 'Motswana, Botswanan' },
  { alpha_3_code: 'BVT', nationality: 'Bouvet Island' },
  { alpha_3_code: 'BRA', nationality: 'Brazilian' },
  { alpha_3_code: 'IOT', nationality: 'BIOT' },
  { alpha_3_code: 'BRN', nationality: 'Bruneian' },
  { alpha_3_code: 'BGR', nationality: 'Bulgarian' },
  { alpha_3_code: 'BFA', nationality: 'Burkinabé' },
  { alpha_3_code: 'BDI', nationality: 'Burundian' },
  { alpha_3_code: 'CPV', nationality: 'Cabo Verdean' },
  { alpha_3_code: 'KHM', nationality: 'Cambodian' },
  { alpha_3_code: 'CMR', nationality: 'Cameroonian' },
  { alpha_3_code: 'CAN', nationality: 'Canadian' },
  { alpha_3_code: 'CYM', nationality: 'Caymanian' },
  { alpha_3_code: 'CAF', nationality: 'Central African' },
  { alpha_3_code: 'TCD', nationality: 'Chadian' },
  { alpha_3_code: 'CHL', nationality: 'Chilean' },
  { alpha_3_code: 'CHN', nationality: 'Chinese' },
  { alpha_3_code: 'CXR', nationality: 'Christmas Island' },
  { alpha_3_code: 'CCK', nationality: 'Cocos Island' },
  { alpha_3_code: 'COL', nationality: 'Colombian' },
  { alpha_3_code: 'COM', nationality: 'Comoran, Comorian' },
  { alpha_3_code: 'COG', nationality: 'Congolese' },
  { alpha_3_code: 'COD', nationality: 'Congolese' },
  { alpha_3_code: 'COK', nationality: 'Cook Island' },
  { alpha_3_code: 'CRI', nationality: 'Costa Rican' },
  { alpha_3_code: 'CIV', nationality: 'Ivorian' },
  { alpha_3_code: 'HRV', nationality: 'Croatian' },
  { alpha_3_code: 'CUB', nationality: 'Cuban' },
  { alpha_3_code: 'CUW', nationality: 'Curaçaoan' },
  { alpha_3_code: 'CYP', nationality: 'Cypriot' },
  { alpha_3_code: 'CZE', nationality: 'Czech' },
  { alpha_3_code: 'DNK', nationality: 'Danish' },
  { alpha_3_code: 'DJI', nationality: 'Djiboutian' },
  { alpha_3_code: 'DMA', nationality: 'Dominican' },
  { alpha_3_code: 'DOM', nationality: 'Dominican' },
  { alpha_3_code: 'ECU', nationality: 'Ecuadorian' },
  { alpha_3_code: 'EGY', nationality: 'Egyptian' },
  { alpha_3_code: 'SLV', nationality: 'Salvadoran' },
  { alpha_3_code: 'GNQ', nationality: 'Equatorial Guinean, Equatoguinean' },
  { alpha_3_code: 'ERI', nationality: 'Eritrean' },
  { alpha_3_code: 'EST', nationality: 'Estonian' },
  { alpha_3_code: 'ETH', nationality: 'Ethiopian' },
  { alpha_3_code: 'FLK', nationality: 'Falkland Island' },
  { alpha_3_code: 'FRO', nationality: 'Faroese' },
  { alpha_3_code: 'FJI', nationality: 'Fijian' },
  { alpha_3_code: 'FIN', nationality: 'Finnish' },
  { alpha_3_code: 'FRA', nationality: 'French' },
  { alpha_3_code: 'GUF', nationality: 'French Guianese' },
  { alpha_3_code: 'PYF', nationality: 'French Polynesian' },
  { alpha_3_code: 'ATF', nationality: 'French Southern Territories' },
  { alpha_3_code: 'GAB', nationality: 'Gabonese' },
  { alpha_3_code: 'GMB', nationality: 'Gambian' },
  { alpha_3_code: 'GEO', nationality: 'Georgian' },
  { alpha_3_code: 'DEU', nationality: 'German' },
  { alpha_3_code: 'GHA', nationality: 'Ghanaian' },
  { alpha_3_code: 'GIB', nationality: 'Gibraltar' },
  { alpha_3_code: 'GRC', nationality: 'Greek, Hellenic' },
  { alpha_3_code: 'GRL', nationality: 'Greenlandic' },
  { alpha_3_code: 'GRD', nationality: 'Grenadian' },
  { alpha_3_code: 'GLP', nationality: 'Guadeloupe' },
  { alpha_3_code: 'GUM', nationality: 'Guamanian, Guambat' },
  { alpha_3_code: 'GTM', nationality: 'Guatemalan' },
  { alpha_3_code: 'GGY', nationality: 'Channel Island' },
  { alpha_3_code: 'GIN', nationality: 'Guinean' },
  { alpha_3_code: 'GNB', nationality: 'Bissau-Guinean' },
  { alpha_3_code: 'GUY', nationality: 'Guyanese' },
  { alpha_3_code: 'HTI', nationality: 'Haitian' },
  { alpha_3_code: 'HMD', nationality: 'Heard Island or McDonald Islands' },
  { alpha_3_code: 'VAT', nationality: 'Vatican' },
  { alpha_3_code: 'HND', nationality: 'Honduran' },
  { alpha_3_code: 'HKG', nationality: 'Hong Kong, Hong Kongese' },
  { alpha_3_code: 'HUN', nationality: 'Hungarian, Magyar' },
  { alpha_3_code: 'ISL', nationality: 'Icelandic' },
  { alpha_3_code: 'IND', nationality: 'Indian' },
  { alpha_3_code: 'IDN', nationality: 'Indonesian' },
  { alpha_3_code: 'IRN', nationality: 'Iranian, Persian' },
  { alpha_3_code: 'IRQ', nationality: 'Iraqi' },
  { alpha_3_code: 'IRL', nationality: 'Irish' },
  { alpha_3_code: 'IMN', nationality: 'Manx' },
  { alpha_3_code: 'ISR', nationality: 'Israeli' },
  { alpha_3_code: 'ITA', nationality: 'Italian' },
  { alpha_3_code: 'JAM', nationality: 'Jamaican' },
  { alpha_3_code: 'JPN', nationality: 'Japanese' },
  { alpha_3_code: 'JEY', nationality: 'Channel Island' },
  { alpha_3_code: 'JOR', nationality: 'Jordanian' },
  { alpha_3_code: 'KAZ', nationality: 'Kazakhstani, Kazakh' },
  { alpha_3_code: 'KEN', nationality: 'Kenyan' },
  { alpha_3_code: 'KIR', nationality: 'I-Kiribati' },
  { alpha_3_code: 'PRK', nationality: 'North Korean' },
  { alpha_3_code: 'KOR', nationality: 'South Korean' },
  { alpha_3_code: 'KWT', nationality: 'Kuwaiti' },
  { alpha_3_code: 'KGZ', nationality: 'Kyrgyzstani, Kyrgyz, Kirgiz, Kirghiz' },
  { alpha_3_code: 'LAO', nationality: 'Lao, Laotian' },
  { alpha_3_code: 'LVA', nationality: 'Latvian' },
  { alpha_3_code: 'LBN', nationality: 'Lebanese' },
  { alpha_3_code: 'LSO', nationality: 'Basotho' },
  { alpha_3_code: 'LBR', nationality: 'Liberian' },
  { alpha_3_code: 'LBY', nationality: 'Libyan' },
  { alpha_3_code: 'LIE', nationality: 'Liechtenstein' },
  { alpha_3_code: 'LTU', nationality: 'Lithuanian' },
  { alpha_3_code: 'LUX', nationality: 'Luxembourg, Luxembourgish' },
  { alpha_3_code: 'MAC', nationality: 'Macanese, Chinese' },
  { alpha_3_code: 'MKD', nationality: 'Macedonian' },
  { alpha_3_code: 'MDG', nationality: 'Malagasy' },
  { alpha_3_code: 'MWI', nationality: 'Malawian' },
  { alpha_3_code: 'MYS', nationality: 'Malaysian' },
  { alpha_3_code: 'MDV', nationality: 'Maldivian' },
  { alpha_3_code: 'MLI', nationality: 'Malian, Malinese' },
  { alpha_3_code: 'MLT', nationality: 'Maltese' },
  { alpha_3_code: 'MHL', nationality: 'Marshallese' },
  { alpha_3_code: 'MTQ', nationality: 'Martiniquais, Martinican' },
  { alpha_3_code: 'MRT', nationality: 'Mauritanian' },
  { alpha_3_code: 'MUS', nationality: 'Mauritian' },
  { alpha_3_code: 'MYT', nationality: 'Mahoran' },
  { alpha_3_code: 'MEX', nationality: 'Mexican' },
  { alpha_3_code: 'FSM', nationality: 'Micronesian' },
  { alpha_3_code: 'MDA', nationality: 'Moldovan' },
  { alpha_3_code: 'MCO', nationality: 'Monégasque, Monacan' },
  { alpha_3_code: 'MNG', nationality: 'Mongolian' },
  { alpha_3_code: 'MNE', nationality: 'Montenegrin' },
  { alpha_3_code: 'MSR', nationality: 'Montserratian' },
  { alpha_3_code: 'MAR', nationality: 'Moroccan' },
  { alpha_3_code: 'MOZ', nationality: 'Mozambican' },
  { alpha_3_code: 'MMR', nationality: 'Burmese' },
  { alpha_3_code: 'NAM', nationality: 'Namibian' },
  { alpha_3_code: 'NRU', nationality: 'Nauruan' },
  { alpha_3_code: 'NPL', nationality: 'Nepali, Nepalese' },
  { alpha_3_code: 'NLD', nationality: 'Dutch, Netherlandic' },
  { alpha_3_code: 'NCL', nationality: 'New Caledonian' },
  { alpha_3_code: 'NZL', nationality: 'New Zealand, NZ' },
  { alpha_3_code: 'NIC', nationality: 'Nicaraguan' },
  { alpha_3_code: 'NER', nationality: 'Nigerien' },
  { alpha_3_code: 'NGA', nationality: 'Nigerian' },
  { alpha_3_code: 'NIU', nationality: 'Niuean' },
  { alpha_3_code: 'NFK', nationality: 'Norfolk Island' },
  { alpha_3_code: 'MNP', nationality: 'Northern Marianan' },
  { alpha_3_code: 'NOR', nationality: 'Norwegian' },
  { alpha_3_code: 'OMN', nationality: 'Omani' },
  { alpha_3_code: 'PAK', nationality: 'Pakistani' },
  { alpha_3_code: 'PLW', nationality: 'Palauan' },
  { alpha_3_code: 'PSE', nationality: 'Palestinian' },
  { alpha_3_code: 'PAN', nationality: 'Panamanian' },
  { alpha_3_code: 'PNG', nationality: 'Papua New Guinean, Papuan' },
  { alpha_3_code: 'PRY', nationality: 'Paraguayan' },
  { alpha_3_code: 'PER', nationality: 'Peruvian' },
  { alpha_3_code: 'PHL', nationality: 'Philippine, Filipino' },
  { alpha_3_code: 'PCN', nationality: 'Pitcairn Island' },
  { alpha_3_code: 'POL', nationality: 'Polish' },
  { alpha_3_code: 'PRT', nationality: 'Portuguese' },
  { alpha_3_code: 'PRI', nationality: 'Puerto Rican' },
  { alpha_3_code: 'QAT', nationality: 'Qatari' },
  { alpha_3_code: 'REU', nationality: 'Réunionese, Réunionnais' },
  { alpha_3_code: 'ROU', nationality: 'Romanian' },
  { alpha_3_code: 'RUS', nationality: 'Russian' },
  { alpha_3_code: 'RWA', nationality: 'Rwandan' },
  { alpha_3_code: 'BLM', nationality: 'Barthélemois' },
  { alpha_3_code: 'SHN', nationality: 'Saint Helenian' },
  { alpha_3_code: 'KNA', nationality: 'Kittitian or Nevisian' },
  { alpha_3_code: 'LCA', nationality: 'Saint Lucian' },
  { alpha_3_code: 'MAF', nationality: 'Saint-Martinoise' },
  { alpha_3_code: 'SPM', nationality: 'Saint-Pierrais or Miquelonnais' },
  { alpha_3_code: 'VCT', nationality: 'Saint Vincentian, Vincentian' },
  { alpha_3_code: 'WSM', nationality: 'Samoan' },
  { alpha_3_code: 'SMR', nationality: 'Sammarinese' },
  { alpha_3_code: 'STP', nationality: 'São Toméan' },
  { alpha_3_code: 'SAU', nationality: 'Saudi, Saudi Arabian' },
  { alpha_3_code: 'SEN', nationality: 'Senegalese' },
  { alpha_3_code: 'SRB', nationality: 'Serbian' },
  { alpha_3_code: 'SYC', nationality: 'Seychellois' },
  { alpha_3_code: 'SLE', nationality: 'Sierra Leonean' },
  { alpha_3_code: 'SGP', nationality: 'Singaporean' },
  { alpha_3_code: 'SXM', nationality: 'Sint Maarten' },
  { alpha_3_code: 'SVK', nationality: 'Slovak' },
  { alpha_3_code: 'SVN', nationality: 'Slovenian, Slovene' },
  { alpha_3_code: 'SLB', nationality: 'Solomon Island' },
  { alpha_3_code: 'SOM', nationality: 'Somali, Somalian' },
  { alpha_3_code: 'ZAF', nationality: 'South African' },
  { alpha_3_code: 'SGS', nationality: 'South Georgia or South Sandwich Islands' },
  { alpha_3_code: 'SSD', nationality: 'South Sudanese' },
  { alpha_3_code: 'ESP', nationality: 'Spanish' },
  { alpha_3_code: 'LKA', nationality: 'Sri Lankan' },
  { alpha_3_code: 'SDN', nationality: 'Sudanese' },
  { alpha_3_code: 'SUR', nationality: 'Surinamese' },
  { alpha_3_code: 'SJM', nationality: 'Svalbard' },
  { alpha_3_code: 'SWZ', nationality: 'Swazi' },
  { alpha_3_code: 'SWE', nationality: 'Swedish' },
  { alpha_3_code: 'CHE', nationality: 'Swiss' },
  { alpha_3_code: 'SYR', nationality: 'Syrian' },
  { alpha_3_code: 'TWN', nationality: 'Chinese, Taiwanese' },
  { alpha_3_code: 'TJK', nationality: 'Tajikistani' },
  { alpha_3_code: 'TZA', nationality: 'Tanzanian' },
  { alpha_3_code: 'THA', nationality: 'Thai' },
  { alpha_3_code: 'TLS', nationality: 'Timorese' },
  { alpha_3_code: 'TGO', nationality: 'Togolese' },
  { alpha_3_code: 'TKL', nationality: 'Tokelauan' },
  { alpha_3_code: 'TON', nationality: 'Tongan' },
  { alpha_3_code: 'TTO', nationality: 'Trinidadian or Tobagonian' },
  { alpha_3_code: 'TUN', nationality: 'Tunisian' },
  { alpha_3_code: 'TUR', nationality: 'Turkish' },
  { alpha_3_code: 'TKM', nationality: 'Turkmen' },
  { alpha_3_code: 'TCA', nationality: 'Turks and Caicos Island' },
  { alpha_3_code: 'TUV', nationality: 'Tuvaluan' },
  { alpha_3_code: 'UGA', nationality: 'Ugandan' },
  { alpha_3_code: 'UKR', nationality: 'Ukrainian' },
  { alpha_3_code: 'ARE', nationality: 'Emirati, Emirian, Emiri' },
  { alpha_3_code: 'GBR', nationality: 'British, UK' },
  { alpha_3_code: 'UMI', nationality: 'American' },
  { alpha_3_code: 'USA', nationality: 'American' },
  { alpha_3_code: 'URY', nationality: 'Uruguayan' },
  { alpha_3_code: 'UZB', nationality: 'Uzbekistani, Uzbek' },
  { alpha_3_code: 'VUT', nationality: 'Ni-Vanuatu, Vanuatuan' },
  { alpha_3_code: 'VEN', nationality: 'Venezuelan' },
  { alpha_3_code: 'VNM', nationality: 'Vietnamese' },
  { alpha_3_code: 'VGB', nationality: 'British Virgin Island' },
  { alpha_3_code: 'VIR', nationality: 'U.S. Virgin Island' },
  { alpha_3_code: 'WLF', nationality: 'Wallis and Futuna, Wallisian or Futunan' },
  { alpha_3_code: 'ESH', nationality: 'Sahrawi, Sahrawian, Sahraouian' },
  { alpha_3_code: 'YEM', nationality: 'Yemeni' },
  { alpha_3_code: 'ZMB', nationality: 'Zambian' },
  { alpha_3_code: 'ZWE', nationality: 'Zimbabwean' },
]

const nationalitiesObject = {}
nationalitiesList.forEach((nationality) => {
  nationalitiesObject[nationality.alpha_3_code] = nationality
})

export { nationalitiesList, nationalitiesObject, NationalityItem }
