const axios = require('axios')
const fs = require('fs')

async function main() {
  const SERVER_BASE_API = 'http://localhost:10081/api'
  const sizes = await axios.get(SERVER_BASE_API + '/all-image-sizes')
  fs.writeFileSync(
    './helpers/imageSizes.ts',
    `/**
 THIS FILE WAS AUTOGENERATED BY THE COMMAND fetch-image-sizes
 */
export const IMAGE_SIZES_VALUES = ${JSON.stringify(sizes.data)}
export const IMAGE_SIZES = {${Object.keys(sizes.data)
      .map((key) => `${key}: '${key}'`)
      .join(', ')}}
`
  )
}

main()
