mutation TransferCandidatesAndClients($fromCompanyId: ObfId!, $toCompanyId: ObfId!) {
  transferCandidatesAndClients(fromCompanyId: $fromCompanyId, toCompanyId: $toCompanyId, trashed: WITH) {
    id
    name
  }
}
