#import "../../fragments/Document.gql"
#import "../../fragments/ImageSizeFormat.gql"
#import "../../fragments/CropProps.gql"

query GetCandidate($id: ObfId!) {
  candidate(id: $id) {
    id
    person {
      id
      title
      firstname
      other_firstnames
      lastname
      birth_name
      gender
      birthdate
      foto {
        id
        sizes {
          PROFILE_IMAGE {
            ...ImageSizeFormat
            ...CropProps
          }
        }
        original_image
      }
    }
    email
    marital_status
    is_blacklisted
    blacklisting_reason
    is_interim
    is_permanent
    skype_name
    desired_job
    max_distance_from_home
    willing_to_travel
    available_from
    daily_rate
    has_hourly_rate
    expenses_included
    period_of_notice
    basic_salary
    bonus_eur
    is_business_car_included
    other_bonus
    notes
    linked_in_profile
    xing_profile
    url
    nationalities {
      id
    }
    is_research
    location {
      id
      full_address
    }
    phonenumbers {
      id
      country_code
      dial_code
      number
      label
    }
    industries {
      id
      title
    }
    skills {
      id
      title
    }
    certifications {
      id
      title
    }
    it_skills {
      id
      title
    }
    worked_at_companies {
      id
      from
      job_title
      job_level
      main_responsibilities
      till
      company {
        id
        name
      }
    }
    languages {
      code
      name
      language_pivot {
        level
      }
    }
    educations {
      id
      institution {
        id
        name
      }
      main_field_of_study
      additional_fields_of_study
      from
      till
      degree
      final_grade
      notes
    }
    zoom_id
    documents {
      ...Document
    }
  }
}
