mutation MoveCandidateToShortlist($candidateId: ObfId!, $projectId: ObfId!, $pivot: CandidateProjectPivotInput) {
  moveCandidateToShortlist(candidateId: $candidateId, projectId: $projectId, pivot: $pivot) {
    id
    candidate_project_pivot {
      is_shortlisted
      status
      purchasing_daily_rate
      retail_daily_rate
      basic_salary
      bonus_eur
    }
  }
}
