#import "../../fragments/EventWithUser.gql"

mutation ThumbDownCandidateByClient($candidateId: ObfId!, $projectId: ObfId!, $note: String) {
  thumbDownCandidateByClient(candidateId: $candidateId, projectId: $projectId, note: $note) {
    candidate {
      id
      candidate_project_pivot {
        liked_by_client
      }
    }
    event {
      ...EventWithUser
    }
  }
}
