mutation SetSettings($reportReadyToInvoiceRevenueTo: JSON) {
  reportReadyToInvoiceRevenueTo: setSetting(key: "reportReadyToInvoiceRevenueTo", value: $reportReadyToInvoiceRevenueTo) {
    key
    value
  }
}
