#import "../../fragments/WorkingHours.gql"

mutation SubmitWorkingHoursRequestToClient($input: UpdateWorkingHoursInput!) {
  submitWorkingHoursRequestToClient(input: $input) {
    ...WorkingHours
  }
}
